export const authCopy = {
  en: {
    login: "Sign in", register: "Create account", username: "Username", password: "Password",
    confirm: "Confirm password", oldPassword: "Current password", newPassword: "New password",
    show: "Show password", hide: "Hide password", remember: "Keep me signed in for 30 days",
    usernameHelp: "3–32 letters, numbers or underscores. Usernames ignore letter case.",
    passwordHelp: "15–128 characters. Spaces and long passphrases are welcome.",
    loginTitle: "Your taste. Everywhere.", registerTitle: "Make room for your next favorite.",
    intro: "Sign in to carry your music preferences from one device to the next.",
    newAccount: "New to Sonora?", existing: "Already have an account?", forgotten: "Forgot your password?",
    recovery: "Contact the project administrator to reset your password. Email recovery is not available.",
    mismatch: "Passwords do not match.", invalidUsername: "Use 3–32 letters, numbers or underscores.",
    invalidPassword: "Password must have 15–128 characters.", busy: "Please wait…", logout: "Sign out",
    change: "Change password", changeTitle: "A fresh password.", save: "Update password",
    changeHelp: "Updating your password signs you out on every device.", checking: "Checking your account…",
    unavailable: "Account service unavailable. Please retry.", retry: "Retry", back: "Back to music",
    invalid_credentials: "Username or password is incorrect.", username_taken: "That username is already taken.",
    auth_rate_limited: "Too many attempts. Please wait 15 minutes before trying again.",
    csrf_invalid: "Your request could not be verified. Please try again.", sessionChanged: "Please sign in again.",
  },
  zh: {
    login: "登录", register: "注册账号", username: "用户名", password: "密码",
    confirm: "确认密码", oldPassword: "当前密码", newPassword: "新密码",
    show: "显示密码", hide: "隐藏密码", remember: "保持登录 30 天",
    usernameHelp: "3–32 位字母、数字或下划线，用户名不区分大小写。",
    passwordHelp: "15–128 个字符，支持空格和长密码。",
    loginTitle: "你的音乐喜好，随你而行。", registerTitle: "从这里，听见新的喜欢。",
    intro: "登录后，在不同设备上延续你的音乐偏好。",
    newAccount: "第一次来到 Sonora？", existing: "已有账号？", forgotten: "忘记密码？",
    recovery: "请联系项目管理员重置密码，暂不提供邮箱找回。",
    mismatch: "两次输入的密码不一致。", invalidUsername: "请使用 3–32 位字母、数字或下划线。",
    invalidPassword: "密码需为 15–128 个字符。", busy: "请稍候…", logout: "退出登录",
    change: "修改密码", changeTitle: "更新你的密码。", save: "更新密码",
    changeHelp: "修改成功后，所有设备都需要重新登录。", checking: "正在验证账号…",
    unavailable: "账号服务暂不可用，请重试。", retry: "重试", back: "返回音乐",
    invalid_credentials: "用户名或密码不正确。", username_taken: "该用户名已被使用。",
    auth_rate_limited: "尝试次数过多，请等待 15 分钟后重试。",
    csrf_invalid: "请求验证失败，请重新尝试。", sessionChanged: "请重新登录。",
  },
};
